### ISSUE TITLE
Content overflows on mobile devices

### ISSUE THREAD

**Issue by CoolOppo** [quixdb/squash-benchmark#12]
Take a look at the site with the device simulator in your browser's developer tools to see what I mean. The page is really, really messed up.

**Comment by CoolOppo** [comment]
![](http://i.imgur.com/Mp6zqX3.png)

**Comment by nemequ** [comment]
Sorry, I'm not a front-end web developer (TBH I didn't even know about "the device simulator in your browser's developer tools").  It seems like this is caused by the tables, mostly the results table.  I used bootstrap (with a theme from bootswatch) for everything, so I've added the table-responsive class to the tables, I hope that's a bit better.  If you are a front-end dev, suggestions are welcome as long as it doesn't ruin the experience on larger devices.

Also, if you rotate your phone things should be a lot better.

That said, I don't think this is going to be a very good resource for a phone without a _lot_ of work (if ever). It's simply too much data for a small screen.  It is okay on a tablet.

**Comment by nemequ** [comment]
One thing I played with during development was having the first three columns in the results table with colspan="3", then using one row each for the compression speed, decompression speed, and ratio graphs (progress bars).  If you know how to make that happen responsively, that would probably solve the issue, and I'd be happy to merge it.

**Comment by CoolOppo** [comment]
> If you know how to make that happen responsively, that would probably solve the issue, and I'd be happy to merge it.

Alright, I'll take a look at it!

**Comment by nemequ** [comment]
Actually, I started to do that (by creating two tables, one with hidden-xs, one with visible-xs), but then I remembered the other reason I wanted to get rid of it—it ruined the possibility of sorting by compression speed, decompression speed, or ratio.

Anyways, things actually look pretty decent for me now as long as I orient my phone in landscape mode, but I'm still open to suggestions.

**Comment by CoolOppo** [comment]
Oh I see something wrong. The class `table-responsive` applies to a `<div>` that contains the table - not the table itself.

**Comment by nemequ** [comment]
Fixed—does that help?

**Comment by CoolOppo** [comment]
Yep.

**Comment by nemequ** [comment]
Excellent.  Thank you very much for figuring this out, it's greatly appreciated.
