### ISSUE TITLE
please add sdch

### ISSUE THREAD

**Issue by solmetricchris** [quixdb/squash-benchmark#3]
I know this particular codec has a very specific use case.  But it is also one of the most common use cases in the modern world, and it would be very interesting to see how it stacks up to the more general codecs out there.

http://lists.w3.org/Archives/Public/ietf-http-wg/2008JulSep/att-0441/Shared_Dictionary_Compression_over_HTTP.pdf

**Comment by nemequ** [comment]
As long as it is possible to compress any data it should be possible to add it, though I'll need a library which implements it instead of a link to the standard proposal.  If there is one, [please open a bug against Squash](https://github.com/quixdb/squash/issues) as this really isn't an issue for the benchmark, it's an issue for the library the benchmark uses to interface with the codecs.
